/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.rahulsom.jansitable;

import java.io.OutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;

public class TableBuilder {
    private List<Column> columns = new ArrayList<>();
    private int padding = 1;
    private OutputStream out = System.out;

    TableBuilder addColumn(Column column) {
        columns.add(column);
        return this;
    }

    TableBuilder addColumn(int width, Column.Alignment alignment) {
        return addColumn(new Column(width, alignment));
    }

    TableBuilder addColumn(int width) {
        return addColumn(new Column(width));
    }

    TableBuilder padding(int padding) {
        this.padding = padding;
        return this;
    }

    TableBuilder writeTo(OutputStream out) {
        this.out = out;
        return this;
    }

    Table build() {
        return new Table(columns, padding, new PrintStream(out));
    }
}
