name: Publish Master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Gradle Caches
        id: cache-gradle-caches
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{hashFiles('**/*.gradle')}}
          path: |
            ~/.gradle/caches
      - name: Cache Gradle Wrapper
        id: cache-gradle-wrapper
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          path: |
            ~/.gradle/wrapper
      - uses: gradle/wrapper-validation-action@v1
        name: Validate Gradle Wrapper

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.PGP_KEY }}
          passphrase: ${{ secrets.PGP_PASSWORD }}
      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import_gpg.outputs.name }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"

      - name: Build with Gradle
        env:
          NEXUS_USER: rahulsom
          NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
          GRGIT_USER: ${{secrets.GH_TOKEN}}
        run: |
          mkdir -p ~/.gradle
          echo "nexusUsername=$NEXUS_USER"     >> ~/.gradle/gradle.properties
          echo "nexusPassword=$NEXUS_PASSWORD" >> ~/.gradle/gradle.properties
          ./gradlew build snapshot --stacktrace --scan
      - uses: codecov/codecov-action@v1
        name: Publish Code Coverage
